import { Link } from 'react-router-dom';
import styled from 'styled-components';
import { text1 } from '../../../../styles/color';

const PostInfo = () => {
  return (
    <PostInfoBox>
      <Link to=''>
        <h4 className='post-title'>Reactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbu</h4>
        <div className='main-text'>
          fkuvbajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbufkuvbajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbufkuvbajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbufkuvbajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbuReactsdfbsdbfsdbgsdfbasdfasdfasdfasdfadsfksajdlfnlkajnsdklvanbsjildvaklsjdnvljabvfahsdbvalsdbvabdsvbaiasdfaadefbvadfbvadfkuvbaeukvbu
        </div>
      </Link>
      <div className='sub-info'>약 7시간 전 · 0개의 댓글</div>
    </PostInfoBox>
  );
};

const PostInfoBox = styled.div`
  display: flex;
  flex: 1 1 0%;
  flex-direction: column;
  padding: 1rem;

  .post-title {
    margin-bottom: 0.25rem;
    font-size: 1rem;
    line-height: 1.5;
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
    color: ${text1};
  }

  .main-text {
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    /* height: 3.9375rem; */
    margin-bottom: 1.5rem;
    overflow-wrap: break-word;
    font-size: 0.875rem;
    line-height: 1.5;
    overflow: hidden;
    text-overflow: ellipsis;
    color: #d9d9d9;
  }

  .sub-info {
    font-size: 0.75rem;
    line-height: 1.5;
    color: #d9d9d9;
  }
`;

export default PostInfo;
